
version: "3.9"

services:
  app:
    build: .
    container_name: athomered_app
    environment:
      # Forzamos DB en carpeta 'data' para persistencia
      - DATABASE_URL=sqlite:///data/athomered.db
      # Activar SMTP via MailHog
      - MAIL_TRANSPORT=smtp
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - SMTP_TLS=false
      - SMTP_FROM=no-reply@athomered.local
      # Algoritmo de password (puede ser bcrypt)
      - PWD_ALGO=argon2
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - dbdata:/app/data
    command: uvicorn app.principal:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - mailhog

  mailhog:
    image: mailhog/mailhog:latest
    container_name: athomered_mailhog
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI

volumes:
  dbdata:
    driver: local
